/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.68 (1.7.4)
 * Generated at: 2017-02-08 12:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fstudents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\t\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("                <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-3.3.7-dist/css/bootstrap.min.css\"/>\n");
      out.write("                <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("\t\t<title>Adding students</title>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("            <script>\n");
      out.write("                var profiles = {\"profiles\" : []};\n");
      out.write("                var students;\n");
      out.write("                var humanVars;\n");
      out.write("                var databaseVars;\n");
      out.write("                \n");
      out.write("                function addProfile()\n");
      out.write("                {\n");
      out.write("                    var popupWindow = window.open(\n");
      out.write("                            \"add_profile.jsp\",'popUpWindow','height=300,width=400,left=10,\\n\\\n");
      out.write("                            top=10,resizable=no,scrollbars=yes,\\n\\\n");
      out.write("                            toolbar=no,menubar=no,location=no,directories=no,status=yes');\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                function register()\n");
      out.write("                {\n");
      out.write("                    var popupWindow = window.open(\n");
      out.write("                            \"register_variable.jsp\",'popUpWindow','height=300,width=400,left=10,\\n\\\n");
      out.write("                            top=10,resizable=no,scrollbars=yes,\\n\\\n");
      out.write("                            toolbar=no,menubar=no,location=no,directories=no,status=yes');\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                function changeAll()\n");
      out.write("                {\n");
      out.write("                    var bool = document.getElementById(\"addAll\").checked;\n");
      out.write("                    var form = document.getElementById(\"form\").children;\n");
      out.write("\n");
      out.write("                    for(item of form) \n");
      out.write("                    {\n");
      out.write("                        if(item.nodeName === \"FIELDSET\")\n");
      out.write("                            item.children[2].checked = bool;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                function postSubmit()\n");
      out.write("                {\n");
      out.write("                    var form = document.getElementById(\"form\");\n");
      out.write("                    var formName = form.name;\n");
      out.write("                    students = {};\n");
      out.write("                    students[formName] = [];\n");
      out.write("                    \n");
      out.write("                    for(item of form.children) \n");
      out.write("                    {\n");
      out.write("                        if(item.nodeName === \"FIELDSET\")\n");
      out.write("                        {\n");
      out.write("                            var elements = item.children;\n");
      out.write("                            \n");
      out.write("                            if(elements[2].checked)\n");
      out.write("                            {\n");
      out.write("                                var student = {};\n");
      out.write("                                student[\"name\"] = elements[0].innerHTML;\n");
      out.write("                                student[\"id\"] = item.id;\n");
      out.write("                                //console.log(\"NAME:\" + elements[0].innerHTML);\n");
      out.write("                                //console.log(\"ID:\" + item.id);\n");
      out.write("                                for(element of elements)\n");
      out.write("                                {\n");
      out.write("                                    if(element.type === \"text\")\n");
      out.write("                                    {\n");
      out.write("                                        //console.log(element.name + \":\" + element.value);\n");
      out.write("                                        student[element.name] = element.value;\n");
      out.write("                                    }\n");
      out.write("                                    else if(element.nodeName === \"SELECT\")\n");
      out.write("                                    {\n");
      out.write("                                        //console.log(element.id + \":\" + element.selectedIndex);\n");
      out.write("                                        student[\"predictor,\" + element.id] = element.selectedIndex;\n");
      out.write("                                    }\n");
      out.write("                                }\n");
      out.write("                                students[formName].push(student);\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                    console.log(students);\n");
      out.write("                    \n");
      out.write("                    var popupWindow = window.open(\n");
      out.write("                            \"print_page.jsp\",'popUpWindow','type=fullWindow,fullscreen,scrollbars=yes');\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("            <input type=\"button\" value=\"Add file profile\" onclick=\"addProfile()\">\n");
      out.write("            <div class=\"divider\"></div>\n");
      out.write("            <input type=\"button\" id=\"registerButton\" value=\"Register variable\" onclick=\"register()\" disabled>\n");
      out.write("            <br><br>\n");
      out.write("            <div id=\"load\" class=\"loader\">\n");
      out.write("                <form id=\"form\" action=\"/majorclassifier\" method=\"get\" style=\"white-space: nowrap\">\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\t</body>\n");
      out.write("\t<script>\n");
      out.write("            var xmlhttp = new XMLHttpRequest();\n");
      out.write("            var url = \"/majorclassifier/AddStudent\";\n");
      out.write("            var params = \"\";\n");
      out.write("\n");
      out.write("            xmlhttp.open(\"Get\", url + params, true);\n");
      out.write("            xmlhttp.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n");
      out.write("\n");
      out.write("            xmlhttp.onreadystatechange = function() \n");
      out.write("            {\n");
      out.write("                if(this.readyState === 4 && this.status === 200)\n");
      out.write("                {\n");
      out.write("                    var myArr = JSON.parse(this.responseText).students;\n");
      out.write("                    //console.log(myArr);\n");
      out.write("                    \n");
      out.write("                    var addAll = document.createElement(\"LABEL\");\n");
      out.write("                    addAll.innerHTML = \"Add all\";\n");
      out.write("                    document.getElementById(\"form\").appendChild(addAll);\n");
      out.write("\n");
      out.write("                    var allAllCheck = document.createElement('INPUT');\n");
      out.write("                    allAllCheck.type = \"checkbox\";\n");
      out.write("                    allAllCheck.id = \"addAll\";\n");
      out.write("                    allAllCheck.setAttribute(\"onclick\", \"changeAll()\");\n");
      out.write("                    document.getElementById(\"form\").appendChild(allAllCheck);\n");
      out.write("\n");
      out.write("                    for(student of myArr)\n");
      out.write("                    {\n");
      out.write("                        if(student.hasOwnProperty(\"NURS\"))\n");
      out.write("                        {\n");
      out.write("                            document.getElementById(\"form\").name = \"NURS\";\n");
      out.write("                            var fieldset = document.createElement(\"FIELDSET\");\n");
      out.write("                            fieldset.id = student.field;\n");
      out.write("\n");
      out.write("                            var legend = document.createElement(\"LEGEND\");\n");
      out.write("                            legend.innerHTML = student.name;\n");
      out.write("                            fieldset.appendChild(legend);\n");
      out.write("                            \n");
      out.write("                            var addLabel = document.createElement(\"LABEL\");\n");
      out.write("                            addLabel.innerHTML = \"Add\";\n");
      out.write("                            fieldset.appendChild(addLabel);\n");
      out.write("\n");
      out.write("                            var checkbox = document.createElement('INPUT');\n");
      out.write("                            checkbox.type = \"checkbox\";\n");
      out.write("                            checkbox.name = \"checkBox\";\n");
      out.write("                            fieldset.appendChild(checkbox);\n");
      out.write("\n");
      out.write("                            var elements = student.NURS;\n");
      out.write("                          \n");
      out.write("                            for(itemName in elements)\n");
      out.write("                            {\n");
      out.write("                                var item = elements[itemName];\n");
      out.write("\n");
      out.write("                                if(itemName === \"files\")\n");
      out.write("                                {\n");
      out.write("                                    var database = item[0].split(\",\");\n");
      out.write("                                    var human = item[1].split(\",\");\n");
      out.write("\n");
      out.write("                                    databaseVars = database;\n");
      out.write("                                    humanVars = human;\n");
      out.write("\n");
      out.write("                                    for(var i = 0; i < human.length; ++i)\n");
      out.write("                                    {\n");
      out.write("                                        var label = document.createElement(\"LABEL\");\n");
      out.write("                                        label.innerHTML = human[i] + \":\";\n");
      out.write("                                        fieldset.appendChild(label);\n");
      out.write("\n");
      out.write("                                        var input = document.createElement(\"INPUT\");\n");
      out.write("                                        input.type = \"text\";\n");
      out.write("                                        input.name = database[i];\n");
      out.write("                                        input.value = \"\";\n");
      out.write("                                        input.setAttribute(\"readonly\", \"true\");\n");
      out.write("                                        fieldset.appendChild(input);\n");
      out.write("                                    }\n");
      out.write("                                    document.getElementById(\"registerButton\").disabled = \"\";\n");
      out.write("                                }\n");
      out.write("                                else if(itemName === \"predictor\")\n");
      out.write("                                {\n");
      out.write("                                    var label = document.createElement(\"LABEL\");\n");
      out.write("                                    label.innerHTML = item[1] + \":\";\n");
      out.write("                                    fieldset.appendChild(label);\n");
      out.write("\n");
      out.write("                                    var input = document.createElement(\"SELECT\");\n");
      out.write("                                    input.id = item[0];\n");
      out.write("\n");
      out.write("                                    var no = document.createElement(\"OPTION\");\n");
      out.write("                                    no.value = \"no\";\n");
      out.write("                                    no.innerHTML = \"no\";\n");
      out.write("                                    no.selected = \"selected\";\n");
      out.write("                                    input.appendChild(no);\n");
      out.write("\n");
      out.write("                                    var yes = document.createElement(\"OPTION\");\n");
      out.write("                                    yes.value = \"yes\";\n");
      out.write("                                    yes.innerHTML = \"yes\";\n");
      out.write("                                    input.appendChild(yes);\n");
      out.write("\n");
      out.write("                                    fieldset.appendChild(input);\n");
      out.write("                                }\n");
      out.write("                                else\n");
      out.write("                                {\n");
      out.write("                                    var label = document.createElement(\"LABEL\");\n");
      out.write("                                    label.innerHTML = item[0] + \":\";\n");
      out.write("                                    fieldset.appendChild(label);\n");
      out.write("\n");
      out.write("                                    var input = document.createElement(\"INPUT\");\n");
      out.write("                                    input.type = \"text\";\n");
      out.write("                                    input.name = itemName;\n");
      out.write("                                    input.value = item[1];\n");
      out.write("                                    input.setAttribute(\"readonly\", \"true\");\n");
      out.write("                                    fieldset.appendChild(input);\n");
      out.write("                                }\n");
      out.write("                            }\n");
      out.write("                            document.getElementById(\"form\").appendChild(fieldset);\n");
      out.write("                            document.getElementById(\"form\").appendChild(document.createElement(\"BR\"));\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    var submitButton = document.createElement(\"INPUT\");\n");
      out.write("                    submitButton.type = \"button\";\n");
      out.write("                    submitButton.value = \"Submit\";\n");
      out.write("                    submitButton.setAttribute(\"onclick\", \"postSubmit()\");\n");
      out.write("                    document.getElementById(\"form\").appendChild(submitButton);\n");
      out.write("                    \n");
      out.write("                    var div = document.createElement(\"DIV\");\n");
      out.write("                    div.className = \"divider\";\n");
      out.write("                    document.getElementById(\"form\").appendChild(div);\n");
      out.write("                    \n");
      out.write("                    var cancelButton = document.createElement(\"INPUT\");\n");
      out.write("                    cancelButton.type = \"button\";\n");
      out.write("                    cancelButton.value = \"Cancel\";\n");
      out.write("                    cancelButton.setAttribute(\"onclick\", \"window.location = \\\"/majorclassifier\\\"\");\n");
      out.write("                    document.getElementById(\"form\").appendChild(cancelButton);\n");
      out.write("                }\n");
      out.write("                document.getElementById(\"load\").className = \"temp\";\n");
      out.write("            };\n");
      out.write("            xmlhttp.send();\n");
      out.write("\t</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
