/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.68 (1.7.4)
 * Generated at: 2017-02-08 12:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap-3.3.7-dist/css/bootstrap.min.css\"/>\n");
      out.write("        <script type=\"text/javascript\" src=\"jquery-3.1.1.min.js\"></script>\n");
      out.write("        <title>Register variable</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <script>\n");
      out.write("            var profiles;\n");
      out.write("            function submitForm()\n");
      out.write("            {\n");
      out.write("                var file = document.getElementById(\"file\");\n");
      out.write("                var name = document.getElementById(\"profileName\").value;\n");
      out.write("                \n");
      out.write("                console.log(file);\n");
      out.write("                \n");
      out.write("                if(file !== null && name != null)\n");
      out.write("                {\n");
      out.write("                    //Code reference here: http://www.aspsnippets.com/Articles/Pass-value-from-child-popup-window-to-parent-page-window-using-JavaScript.aspx\n");
      out.write("                    if (window.opener != null && !window.opener.closed) {\n");
      out.write("                        //var profile = {\"file\" : file, \"name\" : name, \"format\" : format, \"label\" : label - 1, \"sheet\" : sheet - 1};\n");
      out.write("                        var profile = {\"form\" : $(\"form\"), \"name\" : name};\n");
      out.write("                        window.opener.profiles.profiles.push(profile);\n");
      out.write("                    }\n");
      out.write("                    window.close();\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("        <form id=\"form\" method=\"post\" action=\"/majorclassifier/AddStudent\" target=\"postiframe\" encoding='multipart/form-data' enctype='multipart/form-data'>\n");
      out.write("            What will be the name of the profile?<br>\n");
      out.write("            <input type=\"text\" name=\"profileName\" id=\"profileName\" value=\"profile\"><br><br>\n");
      out.write("            What file is the variable in?<br>\n");
      out.write("            <input type=\"file\" name=\"file\" id=\"file\"><br><br>\n");
      out.write("            How are the students labeled in the file?<br>\n");
      out.write("            <select list=\"names\" name=\"format\" id=\"format\">\n");
      out.write("                <option value=\"Malone email\" selected=\"selected\">Malone email</option>\n");
      out.write("                <option value=\"Malone 6 digit ID\">Malone 6 digit ID</option>\n");
      out.write("            </select><br><br>\n");
      out.write("            What column are the labels in?<br>\n");
      out.write("            <input type=\"number\" name=\"label\" id=\"label\" min=\"1\" value=\"1\" onkeydown=\"return false\"><br><br>\n");
      out.write("            What is the sheet number with the data on it?<br>\n");
      out.write("            <input type=\"number\" name=\"sheet\" id=\"sheet\" min=\"1\" value=\"1\" onkeydown=\"return false\"><br><br>\n");
      out.write("            <input type=\"button\" value=\"Add profile\" onclick=\"submitForm()\">\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
