/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.68 (1.7.4)
 * Generated at: 2017-02-08 12:33:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_005fvariable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <script type=\"text/javascript\" src=\"jquery-3.1.1.min.js\"></script>\n");
      out.write("        <title>Register variable</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <script>\n");
      out.write("            var result;\n");
      out.write("            var profiles;\n");
      out.write("            var human;\n");
      out.write("            var database;\n");
      out.write("            function submitForm()\n");
      out.write("            {\n");
      out.write("                var format = document.getElementById(\"format\").selectedIndex - 1;\n");
      out.write("                var variable = document.getElementById(\"variables\").selectedIndex;\n");
      out.write("                var number = document.getElementById(\"number\").value;\n");
      out.write("                \n");
      out.write("                if(format === -1)\n");
      out.write("                {\n");
      out.write("                    alert(\"Please select a profile before submitting.\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                if(variable === 0)\n");
      out.write("                {\n");
      out.write("                    alert(\"Please select a variable before submitting.\");\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                if (window.opener != null && !window.opener.closed) \n");
      out.write("                {\n");
      out.write("                    var profile = profiles.profiles[format];\n");
      out.write("                    console.log(profile);\n");
      out.write("                    \n");
      out.write("                    //Code reference found here: http://stackoverflow.com/a/7909924\n");
      out.write("                    var iframe = $('<iframe name=\"postiframe\" id=\"postiframe\" style=\"display: none\"></iframe>');\n");
      out.write("\n");
      out.write("                    $(\"body\").append(iframe);\n");
      out.write("\n");
      out.write("                    var form = profile.form.append(jQuery('<input>', {\n");
      out.write("                        'name': 'number',\n");
      out.write("                        'value': number,\n");
      out.write("                        'type': 'number'\n");
      out.write("                    }));\n");
      out.write("                    \n");
      out.write("                    $(\"body\").append(form);\n");
      out.write("                    form.submit();\n");
      out.write("\n");
      out.write("                    //jquery .load is deprecated so do not use that, istead\n");
      out.write("                    //use .on(\"load\", --).Example in stackoverflow uses .load.\n");
      out.write("                    //Also, body.innerHTML returns a <pre></pre> element, so\n");
      out.write("                    //we need to take that out.\n");
      out.write("                    $(\"#postiframe\").on(\"load\", function () {\n");
      out.write("                        result = JSON.parse(this.contentWindow.document.body.children[0].innerHTML);\n");
      out.write("                        \n");
      out.write("                        //Code reference here: http://www.aspsnippets.com/Articles/Pass-value-from-child-popup-window-to-parent-page-window-using-JavaScript.aspx\n");
      out.write("                        if (window.opener != null && !window.opener.closed) {\n");
      out.write("                            \n");
      out.write("                            for(student in result)\n");
      out.write("                            {\n");
      out.write("                                console.log(student + \"=\" + result[student]);\n");
      out.write("                                \n");
      out.write("                                var fieldset = window.opener.document.getElementById(student);\n");
      out.write("                                \n");
      out.write("                                if(fieldset !== null)\n");
      out.write("                                {\n");
      out.write("                                    console.log(fieldset);\n");
      out.write("                                    for(var child of fieldset.children)\n");
      out.write("                                    {\n");
      out.write("                                        if(child.name === document.getElementById(\"variables\").options[variable].value)\n");
      out.write("                                            child.value = result[student];\n");
      out.write("                                    }\n");
      out.write("                                }\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                        //window.close();\n");
      out.write("                    });\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("        <form id=\"form\">\n");
      out.write("            Profile:\n");
      out.write("            <select list=\"names\" name=\"format\" id=\"format\">\n");
      out.write("                <option disabled selected=\"selected\">No profile selected</option>\n");
      out.write("            </select><br><br>\n");
      out.write("            Variable:\n");
      out.write("            <select list=\"variables\" name=\"variables\" id=\"variables\">\n");
      out.write("                <option disabled selected=\"selected\">No variable selected</option>\n");
      out.write("            </select><br><br>\n");
      out.write("            Which column number is the variable to search for in?<br>\n");
      out.write("            <input type=\"number\" name=\"number\" id=\"number\" min=\"0\" value=\"0\" onkeydown=\"return false\"><br><br>\n");
      out.write("            <input type=\"button\" value=\"Submit\" onclick=\"submitForm()\">\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        profiles = window.opener.profiles;\n");
      out.write("        human = window.opener.humanVars;\n");
      out.write("        database = window.opener.databaseVars;\n");
      out.write("        \n");
      out.write("        console.log(human);\n");
      out.write("        console.log(database);\n");
      out.write("        \n");
      out.write("        for(index in profiles.profiles)\n");
      out.write("        {\n");
      out.write("            var profile = profiles.profiles[index];\n");
      out.write("            var option = document.createElement(\"OPTION\");\n");
      out.write("            option.value = profile.name;\n");
      out.write("            option.innerHTML = profile.name;\n");
      out.write("            document.getElementById(\"format\").appendChild(option);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        for(index in human)\n");
      out.write("        {\n");
      out.write("            console.log(index);\n");
      out.write("            var option = document.createElement(\"OPTION\");\n");
      out.write("            option.value = database[index];\n");
      out.write("            option.innerHTML = human[index];\n");
      out.write("            document.getElementById(\"variables\").appendChild(option);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
